// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trifon.IDP.Data;

#nullable disable

namespace Trifon.IDP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231006113242_dbinit")]
    partial class dbinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Trifon.IDP.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("GivenName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SecurityCodeExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Suspended")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Trifon.IDP.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Iso")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Iso3")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Numcode")
                        .HasColumnType("int");

                    b.Property<int>("PhoneCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Iso = "AF",
                            Iso3 = "AFG",
                            Name = "Afghanistan",
                            Numcode = 4,
                            PhoneCode = 93
                        },
                        new
                        {
                            Id = 2,
                            Iso = "AL",
                            Iso3 = "ALB",
                            Name = "Albania",
                            Numcode = 8,
                            PhoneCode = 355
                        },
                        new
                        {
                            Id = 3,
                            Iso = "DZ",
                            Iso3 = "DZA",
                            Name = "Algeria",
                            Numcode = 12,
                            PhoneCode = 213
                        },
                        new
                        {
                            Id = 4,
                            Iso = "AS",
                            Iso3 = "ASM",
                            Name = "American Samoa",
                            Numcode = 16,
                            PhoneCode = 1684
                        },
                        new
                        {
                            Id = 5,
                            Iso = "AD",
                            Iso3 = "AND",
                            Name = "Andorra",
                            Numcode = 20,
                            PhoneCode = 376
                        },
                        new
                        {
                            Id = 6,
                            Iso = "AO",
                            Iso3 = "AGO",
                            Name = "Angola",
                            Numcode = 24,
                            PhoneCode = 244
                        },
                        new
                        {
                            Id = 7,
                            Iso = "AI",
                            Iso3 = "AIA",
                            Name = "Anguilla",
                            Numcode = 660,
                            PhoneCode = 1264
                        },
                        new
                        {
                            Id = 8,
                            Iso = "AQ",
                            Name = "Antarctica",
                            Numcode = -1,
                            PhoneCode = 0
                        },
                        new
                        {
                            Id = 9,
                            Iso = "AG",
                            Iso3 = "ATG",
                            Name = "Antigua and Barbuda",
                            Numcode = 28,
                            PhoneCode = 1268
                        },
                        new
                        {
                            Id = 10,
                            Iso = "AR",
                            Iso3 = "ARG",
                            Name = "Argentina",
                            Numcode = 32,
                            PhoneCode = 54
                        },
                        new
                        {
                            Id = 11,
                            Iso = "AM",
                            Iso3 = "ARM",
                            Name = "Armenia",
                            Numcode = 51,
                            PhoneCode = 374
                        },
                        new
                        {
                            Id = 12,
                            Iso = "AW",
                            Iso3 = "ABW",
                            Name = "Aruba",
                            Numcode = 533,
                            PhoneCode = 297
                        },
                        new
                        {
                            Id = 13,
                            Iso = "AU",
                            Iso3 = "AUS",
                            Name = "Australia",
                            Numcode = 36,
                            PhoneCode = 61
                        },
                        new
                        {
                            Id = 14,
                            Iso = "AT",
                            Iso3 = "AUT",
                            Name = "Austria",
                            Numcode = 40,
                            PhoneCode = 43
                        },
                        new
                        {
                            Id = 15,
                            Iso = "AZ",
                            Iso3 = "AZE",
                            Name = "Azerbaijan",
                            Numcode = 31,
                            PhoneCode = 994
                        },
                        new
                        {
                            Id = 16,
                            Iso = "BS",
                            Iso3 = "BHS",
                            Name = "Bahamas",
                            Numcode = 44,
                            PhoneCode = 1242
                        },
                        new
                        {
                            Id = 17,
                            Iso = "BH",
                            Iso3 = "BHR",
                            Name = "Bahrain",
                            Numcode = 48,
                            PhoneCode = 973
                        },
                        new
                        {
                            Id = 18,
                            Iso = "BD",
                            Iso3 = "BGD",
                            Name = "Bangladesh",
                            Numcode = 50,
                            PhoneCode = 880
                        },
                        new
                        {
                            Id = 19,
                            Iso = "BB",
                            Iso3 = "BRB",
                            Name = "Barbados",
                            Numcode = 52,
                            PhoneCode = 1246
                        },
                        new
                        {
                            Id = 20,
                            Iso = "BY",
                            Iso3 = "BLR",
                            Name = "Belarus",
                            Numcode = 112,
                            PhoneCode = 375
                        },
                        new
                        {
                            Id = 21,
                            Iso = "BE",
                            Iso3 = "BEL",
                            Name = "Belgium",
                            Numcode = 56,
                            PhoneCode = 32
                        },
                        new
                        {
                            Id = 22,
                            Iso = "BZ",
                            Iso3 = "BLZ",
                            Name = "Belize",
                            Numcode = 84,
                            PhoneCode = 501
                        },
                        new
                        {
                            Id = 23,
                            Iso = "BJ",
                            Iso3 = "BEN",
                            Name = "Benin",
                            Numcode = 204,
                            PhoneCode = 229
                        },
                        new
                        {
                            Id = 24,
                            Iso = "BM",
                            Iso3 = "BMU",
                            Name = "Bermuda",
                            Numcode = 60,
                            PhoneCode = 1441
                        },
                        new
                        {
                            Id = 25,
                            Iso = "BT",
                            Iso3 = "BTN",
                            Name = "Bhutan",
                            Numcode = 64,
                            PhoneCode = 975
                        },
                        new
                        {
                            Id = 26,
                            Iso = "BO",
                            Iso3 = "BOL",
                            Name = "Bolivia",
                            Numcode = 68,
                            PhoneCode = 591
                        },
                        new
                        {
                            Id = 27,
                            Iso = "BA",
                            Iso3 = "BIH",
                            Name = "Bosnia and Herzegovina",
                            Numcode = 70,
                            PhoneCode = 387
                        },
                        new
                        {
                            Id = 28,
                            Iso = "BW",
                            Iso3 = "BWA",
                            Name = "Botswana",
                            Numcode = 72,
                            PhoneCode = 267
                        },
                        new
                        {
                            Id = 29,
                            Iso = "BV",
                            Name = "Bouvet Island",
                            Numcode = -1,
                            PhoneCode = 0
                        },
                        new
                        {
                            Id = 30,
                            Iso = "BR",
                            Iso3 = "BRA",
                            Name = "Brazil",
                            Numcode = 76,
                            PhoneCode = 55
                        },
                        new
                        {
                            Id = 31,
                            Iso = "IO",
                            Name = "British Indian Ocean Territory",
                            Numcode = -1,
                            PhoneCode = 246
                        },
                        new
                        {
                            Id = 32,
                            Iso = "BN",
                            Iso3 = "BRN",
                            Name = "Brunei Darussalam",
                            Numcode = 96,
                            PhoneCode = 673
                        },
                        new
                        {
                            Id = 33,
                            Iso = "BG",
                            Iso3 = "BGR",
                            Name = "Bulgaria",
                            Numcode = 100,
                            PhoneCode = 359
                        },
                        new
                        {
                            Id = 34,
                            Iso = "BF",
                            Iso3 = "BFA",
                            Name = "Burkina Faso",
                            Numcode = 854,
                            PhoneCode = 226
                        },
                        new
                        {
                            Id = 35,
                            Iso = "BI",
                            Iso3 = "BDI",
                            Name = "Burundi",
                            Numcode = 108,
                            PhoneCode = 257
                        },
                        new
                        {
                            Id = 36,
                            Iso = "KH",
                            Iso3 = "KHM",
                            Name = "Cambodia",
                            Numcode = 116,
                            PhoneCode = 855
                        },
                        new
                        {
                            Id = 37,
                            Iso = "CM",
                            Iso3 = "CMR",
                            Name = "Cameroon",
                            Numcode = 120,
                            PhoneCode = 237
                        },
                        new
                        {
                            Id = 38,
                            Iso = "CA",
                            Iso3 = "CAN",
                            Name = "Canada",
                            Numcode = 124,
                            PhoneCode = 1
                        },
                        new
                        {
                            Id = 39,
                            Iso = "CV",
                            Iso3 = "CPV",
                            Name = "Cape Verde",
                            Numcode = 132,
                            PhoneCode = 238
                        },
                        new
                        {
                            Id = 40,
                            Iso = "KY",
                            Iso3 = "CYM",
                            Name = "Cayman Islands",
                            Numcode = 136,
                            PhoneCode = 1345
                        },
                        new
                        {
                            Id = 41,
                            Iso = "CF",
                            Iso3 = "CAF",
                            Name = "Central African Republic",
                            Numcode = 140,
                            PhoneCode = 236
                        },
                        new
                        {
                            Id = 42,
                            Iso = "TD",
                            Iso3 = "TCD",
                            Name = "Chad",
                            Numcode = 148,
                            PhoneCode = 235
                        },
                        new
                        {
                            Id = 43,
                            Iso = "CL",
                            Iso3 = "CHL",
                            Name = "Chile",
                            Numcode = 152,
                            PhoneCode = 56
                        },
                        new
                        {
                            Id = 44,
                            Iso = "CN",
                            Iso3 = "CHN",
                            Name = "China",
                            Numcode = 156,
                            PhoneCode = 86
                        },
                        new
                        {
                            Id = 45,
                            Iso = "CX",
                            Name = "Christmas Island",
                            Numcode = -1,
                            PhoneCode = 61
                        },
                        new
                        {
                            Id = 46,
                            Iso = "CC",
                            Name = "Cocos (Keeling) Islands",
                            Numcode = -1,
                            PhoneCode = 672
                        },
                        new
                        {
                            Id = 47,
                            Iso = "CO",
                            Iso3 = "COL",
                            Name = "Colombia",
                            Numcode = 170,
                            PhoneCode = 57
                        },
                        new
                        {
                            Id = 48,
                            Iso = "KM",
                            Iso3 = "COM",
                            Name = "Comoros",
                            Numcode = 174,
                            PhoneCode = 269
                        },
                        new
                        {
                            Id = 49,
                            Iso = "CG",
                            Iso3 = "COG",
                            Name = "Congo",
                            Numcode = 178,
                            PhoneCode = 242
                        },
                        new
                        {
                            Id = 50,
                            Iso = "CD",
                            Iso3 = "COD",
                            Name = "Congo, the Democratic Republic of the",
                            Numcode = 180,
                            PhoneCode = 242
                        },
                        new
                        {
                            Id = 51,
                            Iso = "CK",
                            Iso3 = "COK",
                            Name = "Cook Islands",
                            Numcode = 184,
                            PhoneCode = 682
                        },
                        new
                        {
                            Id = 52,
                            Iso = "CR",
                            Iso3 = "CRI",
                            Name = "Costa Rica",
                            Numcode = 188,
                            PhoneCode = 506
                        },
                        new
                        {
                            Id = 53,
                            Iso = "CI",
                            Iso3 = "CIV",
                            Name = "Cote D'Ivoire",
                            Numcode = 384,
                            PhoneCode = 225
                        },
                        new
                        {
                            Id = 54,
                            Iso = "HR",
                            Iso3 = "HRV",
                            Name = "Croatia",
                            Numcode = 191,
                            PhoneCode = 385
                        },
                        new
                        {
                            Id = 55,
                            Iso = "CU",
                            Iso3 = "CUB",
                            Name = "Cuba",
                            Numcode = 192,
                            PhoneCode = 53
                        },
                        new
                        {
                            Id = 56,
                            Iso = "CY",
                            Iso3 = "CYP",
                            Name = "Cyprus",
                            Numcode = 196,
                            PhoneCode = 357
                        },
                        new
                        {
                            Id = 57,
                            Iso = "CZ",
                            Iso3 = "CZE",
                            Name = "Czech Republic",
                            Numcode = 203,
                            PhoneCode = 420
                        },
                        new
                        {
                            Id = 58,
                            Iso = "DK",
                            Iso3 = "DNK",
                            Name = "Denmark",
                            Numcode = 208,
                            PhoneCode = 45
                        },
                        new
                        {
                            Id = 59,
                            Iso = "DJ",
                            Iso3 = "DJI",
                            Name = "Djibouti",
                            Numcode = 262,
                            PhoneCode = 253
                        },
                        new
                        {
                            Id = 60,
                            Iso = "DM",
                            Iso3 = "DMA",
                            Name = "Dominica",
                            Numcode = 212,
                            PhoneCode = 1767
                        },
                        new
                        {
                            Id = 61,
                            Iso = "DO",
                            Iso3 = "DOM",
                            Name = "Dominican Republic",
                            Numcode = 214,
                            PhoneCode = 1809
                        },
                        new
                        {
                            Id = 62,
                            Iso = "EC",
                            Iso3 = "ECU",
                            Name = "Ecuador",
                            Numcode = 218,
                            PhoneCode = 593
                        },
                        new
                        {
                            Id = 63,
                            Iso = "EG",
                            Iso3 = "EGY",
                            Name = "Egypt",
                            Numcode = 818,
                            PhoneCode = 20
                        },
                        new
                        {
                            Id = 64,
                            Iso = "SV",
                            Iso3 = "SLV",
                            Name = "El Salvador",
                            Numcode = 222,
                            PhoneCode = 503
                        },
                        new
                        {
                            Id = 65,
                            Iso = "GQ",
                            Iso3 = "GNQ",
                            Name = "Equatorial Guinea",
                            Numcode = 226,
                            PhoneCode = 240
                        },
                        new
                        {
                            Id = 66,
                            Iso = "ER",
                            Iso3 = "ERI",
                            Name = "Eritrea",
                            Numcode = 232,
                            PhoneCode = 291
                        },
                        new
                        {
                            Id = 67,
                            Iso = "EE",
                            Iso3 = "EST",
                            Name = "Estonia",
                            Numcode = 233,
                            PhoneCode = 372
                        },
                        new
                        {
                            Id = 68,
                            Iso = "ET",
                            Iso3 = "ETH",
                            Name = "Ethiopia",
                            Numcode = 231,
                            PhoneCode = 251
                        },
                        new
                        {
                            Id = 69,
                            Iso = "FK",
                            Iso3 = "FLK",
                            Name = "Falkland Islands (Malvinas)",
                            Numcode = 238,
                            PhoneCode = 500
                        },
                        new
                        {
                            Id = 70,
                            Iso = "FO",
                            Iso3 = "FRO",
                            Name = "Faroe Islands",
                            Numcode = 234,
                            PhoneCode = 298
                        },
                        new
                        {
                            Id = 71,
                            Iso = "FJ",
                            Iso3 = "FJI",
                            Name = "Fiji",
                            Numcode = 242,
                            PhoneCode = 679
                        },
                        new
                        {
                            Id = 72,
                            Iso = "FI",
                            Iso3 = "FIN",
                            Name = "Finland",
                            Numcode = 246,
                            PhoneCode = 358
                        },
                        new
                        {
                            Id = 73,
                            Iso = "FR",
                            Iso3 = "FRA",
                            Name = "France",
                            Numcode = 250,
                            PhoneCode = 33
                        },
                        new
                        {
                            Id = 74,
                            Iso = "GF",
                            Iso3 = "GUF",
                            Name = "French Guiana",
                            Numcode = 254,
                            PhoneCode = 594
                        },
                        new
                        {
                            Id = 75,
                            Iso = "PF",
                            Iso3 = "PYF",
                            Name = "French Polynesia",
                            Numcode = 258,
                            PhoneCode = 689
                        },
                        new
                        {
                            Id = 76,
                            Iso = "TF",
                            Name = "French Southern Territories",
                            Numcode = -1,
                            PhoneCode = 0
                        },
                        new
                        {
                            Id = 77,
                            Iso = "GA",
                            Iso3 = "GAB",
                            Name = "Gabon",
                            Numcode = 266,
                            PhoneCode = 241
                        },
                        new
                        {
                            Id = 78,
                            Iso = "GM",
                            Iso3 = "GMB",
                            Name = "Gambia",
                            Numcode = 270,
                            PhoneCode = 220
                        },
                        new
                        {
                            Id = 79,
                            Iso = "GE",
                            Iso3 = "GEO",
                            Name = "Georgia",
                            Numcode = 268,
                            PhoneCode = 995
                        },
                        new
                        {
                            Id = 80,
                            Iso = "DE",
                            Iso3 = "DEU",
                            Name = "Germany",
                            Numcode = 276,
                            PhoneCode = 49
                        },
                        new
                        {
                            Id = 81,
                            Iso = "GH",
                            Iso3 = "GHA",
                            Name = "Ghana",
                            Numcode = 288,
                            PhoneCode = 233
                        },
                        new
                        {
                            Id = 82,
                            Iso = "GI",
                            Iso3 = "GIB",
                            Name = "Gibraltar",
                            Numcode = 292,
                            PhoneCode = 350
                        },
                        new
                        {
                            Id = 83,
                            Iso = "GR",
                            Iso3 = "GRC",
                            Name = "Greece",
                            Numcode = 300,
                            PhoneCode = 30
                        },
                        new
                        {
                            Id = 84,
                            Iso = "GL",
                            Iso3 = "GRL",
                            Name = "Greenland",
                            Numcode = 304,
                            PhoneCode = 299
                        },
                        new
                        {
                            Id = 85,
                            Iso = "GD",
                            Iso3 = "GRD",
                            Name = "Grenada",
                            Numcode = 308,
                            PhoneCode = 1473
                        },
                        new
                        {
                            Id = 86,
                            Iso = "GP",
                            Iso3 = "GLP",
                            Name = "Guadeloupe",
                            Numcode = 312,
                            PhoneCode = 590
                        },
                        new
                        {
                            Id = 87,
                            Iso = "GU",
                            Iso3 = "GUM",
                            Name = "Guam",
                            Numcode = 316,
                            PhoneCode = 1671
                        },
                        new
                        {
                            Id = 88,
                            Iso = "GT",
                            Iso3 = "GTM",
                            Name = "Guatemala",
                            Numcode = 320,
                            PhoneCode = 502
                        },
                        new
                        {
                            Id = 89,
                            Iso = "GN",
                            Iso3 = "GIN",
                            Name = "Guinea",
                            Numcode = 324,
                            PhoneCode = 224
                        },
                        new
                        {
                            Id = 90,
                            Iso = "GW",
                            Iso3 = "GNB",
                            Name = "Guinea-Bissau",
                            Numcode = 624,
                            PhoneCode = 245
                        },
                        new
                        {
                            Id = 91,
                            Iso = "GY",
                            Iso3 = "GUY",
                            Name = "Guyana",
                            Numcode = 328,
                            PhoneCode = 592
                        },
                        new
                        {
                            Id = 92,
                            Iso = "HT",
                            Iso3 = "HTI",
                            Name = "Haiti",
                            Numcode = 332,
                            PhoneCode = 509
                        },
                        new
                        {
                            Id = 93,
                            Iso = "HM",
                            Name = "Heard Island and Mcdonald Islands",
                            Numcode = -1,
                            PhoneCode = 0
                        },
                        new
                        {
                            Id = 94,
                            Iso = "VA",
                            Iso3 = "VAT",
                            Name = "Holy See (Vatican City State)",
                            Numcode = 336,
                            PhoneCode = 39
                        },
                        new
                        {
                            Id = 95,
                            Iso = "HN",
                            Iso3 = "HND",
                            Name = "Honduras",
                            Numcode = 340,
                            PhoneCode = 504
                        },
                        new
                        {
                            Id = 96,
                            Iso = "HK",
                            Iso3 = "HKG",
                            Name = "Hong Kong",
                            Numcode = 344,
                            PhoneCode = 852
                        },
                        new
                        {
                            Id = 97,
                            Iso = "HU",
                            Iso3 = "HUN",
                            Name = "Hungary",
                            Numcode = 348,
                            PhoneCode = 36
                        },
                        new
                        {
                            Id = 98,
                            Iso = "IS",
                            Iso3 = "ISL",
                            Name = "Iceland",
                            Numcode = 352,
                            PhoneCode = 354
                        },
                        new
                        {
                            Id = 99,
                            Iso = "IN",
                            Iso3 = "IND",
                            Name = "India",
                            Numcode = 356,
                            PhoneCode = 91
                        },
                        new
                        {
                            Id = 100,
                            Iso = "ID",
                            Iso3 = "IDN",
                            Name = "Indonesia",
                            Numcode = 360,
                            PhoneCode = 62
                        },
                        new
                        {
                            Id = 101,
                            Iso = "IR",
                            Iso3 = "IRN",
                            Name = "Iran, Islamic Republic of",
                            Numcode = 364,
                            PhoneCode = 98
                        },
                        new
                        {
                            Id = 102,
                            Iso = "IQ",
                            Iso3 = "IRQ",
                            Name = "Iraq",
                            Numcode = 368,
                            PhoneCode = 964
                        },
                        new
                        {
                            Id = 103,
                            Iso = "IE",
                            Iso3 = "IRL",
                            Name = "Ireland",
                            Numcode = 372,
                            PhoneCode = 353
                        },
                        new
                        {
                            Id = 104,
                            Iso = "IL",
                            Iso3 = "ISR",
                            Name = "Israel",
                            Numcode = 376,
                            PhoneCode = 972
                        },
                        new
                        {
                            Id = 105,
                            Iso = "IT",
                            Iso3 = "ITA",
                            Name = "Italy",
                            Numcode = 380,
                            PhoneCode = 39
                        },
                        new
                        {
                            Id = 106,
                            Iso = "JM",
                            Iso3 = "JAM",
                            Name = "Jamaica",
                            Numcode = 388,
                            PhoneCode = 1876
                        },
                        new
                        {
                            Id = 107,
                            Iso = "JP",
                            Iso3 = "JPN",
                            Name = "Japan",
                            Numcode = 392,
                            PhoneCode = 81
                        },
                        new
                        {
                            Id = 108,
                            Iso = "JO",
                            Iso3 = "JOR",
                            Name = "Jordan",
                            Numcode = 400,
                            PhoneCode = 962
                        },
                        new
                        {
                            Id = 109,
                            Iso = "KZ",
                            Iso3 = "KAZ",
                            Name = "Kazakhstan",
                            Numcode = 398,
                            PhoneCode = 7
                        },
                        new
                        {
                            Id = 110,
                            Iso = "KE",
                            Iso3 = "KEN",
                            Name = "Kenya",
                            Numcode = 404,
                            PhoneCode = 254
                        },
                        new
                        {
                            Id = 111,
                            Iso = "KI",
                            Iso3 = "KIR",
                            Name = "Kiribati",
                            Numcode = 296,
                            PhoneCode = 686
                        },
                        new
                        {
                            Id = 112,
                            Iso = "KP",
                            Iso3 = "PRK",
                            Name = "Korea, Democratic People's Republic of",
                            Numcode = 408,
                            PhoneCode = 850
                        },
                        new
                        {
                            Id = 113,
                            Iso = "KR",
                            Iso3 = "KOR",
                            Name = "Korea, Republic of",
                            Numcode = 410,
                            PhoneCode = 82
                        },
                        new
                        {
                            Id = 114,
                            Iso = "KW",
                            Iso3 = "KWT",
                            Name = "Kuwait",
                            Numcode = 414,
                            PhoneCode = 965
                        },
                        new
                        {
                            Id = 115,
                            Iso = "KG",
                            Iso3 = "KGZ",
                            Name = "Kyrgyzstan",
                            Numcode = 417,
                            PhoneCode = 996
                        },
                        new
                        {
                            Id = 116,
                            Iso = "LA",
                            Iso3 = "LAO",
                            Name = "Lao People's Democratic Republic",
                            Numcode = 418,
                            PhoneCode = 856
                        },
                        new
                        {
                            Id = 117,
                            Iso = "LV",
                            Iso3 = "LVA",
                            Name = "Latvia",
                            Numcode = 428,
                            PhoneCode = 371
                        },
                        new
                        {
                            Id = 118,
                            Iso = "LB",
                            Iso3 = "LBN",
                            Name = "Lebanon",
                            Numcode = 422,
                            PhoneCode = 961
                        },
                        new
                        {
                            Id = 119,
                            Iso = "LS",
                            Iso3 = "LSO",
                            Name = "Lesotho",
                            Numcode = 426,
                            PhoneCode = 266
                        },
                        new
                        {
                            Id = 120,
                            Iso = "LR",
                            Iso3 = "LBR",
                            Name = "Liberia",
                            Numcode = 430,
                            PhoneCode = 231
                        },
                        new
                        {
                            Id = 121,
                            Iso = "LY",
                            Iso3 = "LBY",
                            Name = "Libyan Arab Jamahiriya",
                            Numcode = 434,
                            PhoneCode = 218
                        },
                        new
                        {
                            Id = 122,
                            Iso = "LI",
                            Iso3 = "LIE",
                            Name = "Liechtenstein",
                            Numcode = 438,
                            PhoneCode = 423
                        },
                        new
                        {
                            Id = 123,
                            Iso = "LT",
                            Iso3 = "LTU",
                            Name = "Lithuania",
                            Numcode = 440,
                            PhoneCode = 370
                        },
                        new
                        {
                            Id = 124,
                            Iso = "LU",
                            Iso3 = "LUX",
                            Name = "Luxembourg",
                            Numcode = 442,
                            PhoneCode = 352
                        },
                        new
                        {
                            Id = 125,
                            Iso = "MO",
                            Iso3 = "MAC",
                            Name = "Macao",
                            Numcode = 446,
                            PhoneCode = 853
                        },
                        new
                        {
                            Id = 126,
                            Iso = "MK",
                            Iso3 = "MKD",
                            Name = "Macedonia, the Former Yugoslav Republic of",
                            Numcode = 807,
                            PhoneCode = 389
                        },
                        new
                        {
                            Id = 127,
                            Iso = "MG",
                            Iso3 = "MDG",
                            Name = "Madagascar",
                            Numcode = 450,
                            PhoneCode = 261
                        },
                        new
                        {
                            Id = 128,
                            Iso = "MW",
                            Iso3 = "MWI",
                            Name = "Malawi",
                            Numcode = 454,
                            PhoneCode = 265
                        },
                        new
                        {
                            Id = 129,
                            Iso = "MY",
                            Iso3 = "MYS",
                            Name = "Malaysia",
                            Numcode = 458,
                            PhoneCode = 60
                        },
                        new
                        {
                            Id = 130,
                            Iso = "MV",
                            Iso3 = "MDV",
                            Name = "Maldives",
                            Numcode = 462,
                            PhoneCode = 960
                        },
                        new
                        {
                            Id = 131,
                            Iso = "ML",
                            Iso3 = "MLI",
                            Name = "Mali",
                            Numcode = 466,
                            PhoneCode = 223
                        },
                        new
                        {
                            Id = 132,
                            Iso = "MT",
                            Iso3 = "MLT",
                            Name = "Malta",
                            Numcode = 470,
                            PhoneCode = 356
                        },
                        new
                        {
                            Id = 133,
                            Iso = "MH",
                            Iso3 = "MHL",
                            Name = "Marshall Islands",
                            Numcode = 584,
                            PhoneCode = 692
                        },
                        new
                        {
                            Id = 134,
                            Iso = "MQ",
                            Iso3 = "MTQ",
                            Name = "Martinique",
                            Numcode = 474,
                            PhoneCode = 596
                        },
                        new
                        {
                            Id = 135,
                            Iso = "MR",
                            Iso3 = "MRT",
                            Name = "Mauritania",
                            Numcode = 478,
                            PhoneCode = 222
                        },
                        new
                        {
                            Id = 136,
                            Iso = "MU",
                            Iso3 = "MUS",
                            Name = "Mauritius",
                            Numcode = 480,
                            PhoneCode = 230
                        },
                        new
                        {
                            Id = 137,
                            Iso = "YT",
                            Iso3 = "MYT",
                            Name = "Mayotte",
                            Numcode = 1758,
                            PhoneCode = 262
                        },
                        new
                        {
                            Id = 138,
                            Iso = "MX",
                            Iso3 = "MEX",
                            Name = "Mexico",
                            Numcode = 484,
                            PhoneCode = 52
                        },
                        new
                        {
                            Id = 139,
                            Iso = "FM",
                            Iso3 = "FSM",
                            Name = "Micronesia, Federated States of",
                            Numcode = 583,
                            PhoneCode = 691
                        },
                        new
                        {
                            Id = 140,
                            Iso = "MD",
                            Iso3 = "MDA",
                            Name = "Moldova, Republic of",
                            Numcode = 498,
                            PhoneCode = 373
                        },
                        new
                        {
                            Id = 141,
                            Iso = "MC",
                            Iso3 = "MCO",
                            Name = "Monaco",
                            Numcode = 492,
                            PhoneCode = 377
                        },
                        new
                        {
                            Id = 142,
                            Iso = "MN",
                            Iso3 = "MNG",
                            Name = "Mongolia",
                            Numcode = 496,
                            PhoneCode = 976
                        },
                        new
                        {
                            Id = 143,
                            Iso = "MS",
                            Iso3 = "MSR",
                            Name = "Montserrat",
                            Numcode = 500,
                            PhoneCode = 1664
                        },
                        new
                        {
                            Id = 144,
                            Iso = "MA",
                            Iso3 = "MAR",
                            Name = "Morocco",
                            Numcode = 504,
                            PhoneCode = 212
                        },
                        new
                        {
                            Id = 145,
                            Iso = "MZ",
                            Iso3 = "MOZ",
                            Name = "Mozambique",
                            Numcode = 508,
                            PhoneCode = 258
                        },
                        new
                        {
                            Id = 146,
                            Iso = "MM",
                            Iso3 = "MMR",
                            Name = "Myanmar",
                            Numcode = 104,
                            PhoneCode = 95
                        },
                        new
                        {
                            Id = 147,
                            Iso = "NA",
                            Iso3 = "NAM",
                            Name = "Namibia",
                            Numcode = 516,
                            PhoneCode = 264
                        },
                        new
                        {
                            Id = 148,
                            Iso = "NR",
                            Iso3 = "NRU",
                            Name = "Nauru",
                            Numcode = 520,
                            PhoneCode = 674
                        },
                        new
                        {
                            Id = 149,
                            Iso = "NP",
                            Iso3 = "NPL",
                            Name = "Nepal",
                            Numcode = 524,
                            PhoneCode = 977
                        },
                        new
                        {
                            Id = 150,
                            Iso = "NL",
                            Iso3 = "NLD",
                            Name = "Netherlands",
                            Numcode = 528,
                            PhoneCode = 31
                        },
                        new
                        {
                            Id = 151,
                            Iso = "AN",
                            Iso3 = "ANT",
                            Name = "Netherlands Antilles",
                            Numcode = 530,
                            PhoneCode = 599
                        },
                        new
                        {
                            Id = 152,
                            Iso = "NC",
                            Iso3 = "NCL",
                            Name = "New Caledonia",
                            Numcode = 540,
                            PhoneCode = 687
                        },
                        new
                        {
                            Id = 153,
                            Iso = "NZ",
                            Iso3 = "NZL",
                            Name = "New Zealand",
                            Numcode = 554,
                            PhoneCode = 64
                        },
                        new
                        {
                            Id = 154,
                            Iso = "NI",
                            Iso3 = "NIC",
                            Name = "Nicaragua",
                            Numcode = 558,
                            PhoneCode = 505
                        },
                        new
                        {
                            Id = 155,
                            Iso = "NE",
                            Iso3 = "NER",
                            Name = "Niger",
                            Numcode = 562,
                            PhoneCode = 227
                        },
                        new
                        {
                            Id = 156,
                            Iso = "NG",
                            Iso3 = "NGA",
                            Name = "Nigeria",
                            Numcode = 566,
                            PhoneCode = 234
                        },
                        new
                        {
                            Id = 157,
                            Iso = "NU",
                            Iso3 = "NIU",
                            Name = "Niue",
                            Numcode = 570,
                            PhoneCode = 683
                        },
                        new
                        {
                            Id = 158,
                            Iso = "NF",
                            Iso3 = "NFK",
                            Name = "Norfolk Island",
                            Numcode = 574,
                            PhoneCode = 672
                        },
                        new
                        {
                            Id = 159,
                            Iso = "MP",
                            Iso3 = "MNP",
                            Name = "Northern Mariana Islands",
                            Numcode = 580,
                            PhoneCode = 1670
                        },
                        new
                        {
                            Id = 160,
                            Iso = "NO",
                            Iso3 = "NOR",
                            Name = "Norway",
                            Numcode = 578,
                            PhoneCode = 47
                        },
                        new
                        {
                            Id = 161,
                            Iso = "OM",
                            Iso3 = "OMN",
                            Name = "Oman",
                            Numcode = 512,
                            PhoneCode = 968
                        },
                        new
                        {
                            Id = 162,
                            Iso = "PK",
                            Iso3 = "PAK",
                            Name = "Pakistan",
                            Numcode = 586,
                            PhoneCode = 92
                        },
                        new
                        {
                            Id = 163,
                            Iso = "PW",
                            Iso3 = "PLW",
                            Name = "Palau",
                            Numcode = 585,
                            PhoneCode = 680
                        },
                        new
                        {
                            Id = 164,
                            Iso = "PS",
                            Iso3 = "PSE",
                            Name = "Palestinian Territory, Occupied",
                            Numcode = 275,
                            PhoneCode = 970
                        },
                        new
                        {
                            Id = 165,
                            Iso = "PA",
                            Iso3 = "PAN",
                            Name = "Panama",
                            Numcode = 591,
                            PhoneCode = 507
                        },
                        new
                        {
                            Id = 166,
                            Iso = "PG",
                            Iso3 = "PNG",
                            Name = "Papua New Guinea",
                            Numcode = 598,
                            PhoneCode = 675
                        },
                        new
                        {
                            Id = 167,
                            Iso = "PY",
                            Iso3 = "PRY",
                            Name = "Paraguay",
                            Numcode = 600,
                            PhoneCode = 595
                        },
                        new
                        {
                            Id = 168,
                            Iso = "PE",
                            Iso3 = "PER",
                            Name = "Peru",
                            Numcode = 604,
                            PhoneCode = 51
                        },
                        new
                        {
                            Id = 169,
                            Iso = "PH",
                            Iso3 = "PHL",
                            Name = "Philippines",
                            Numcode = 608,
                            PhoneCode = 63
                        },
                        new
                        {
                            Id = 170,
                            Iso = "PN",
                            Iso3 = "PCN",
                            Name = "Pitcairn",
                            Numcode = 612,
                            PhoneCode = 0
                        },
                        new
                        {
                            Id = 171,
                            Iso = "PL",
                            Iso3 = "POL",
                            Name = "Poland",
                            Numcode = 616,
                            PhoneCode = 48
                        },
                        new
                        {
                            Id = 172,
                            Iso = "PT",
                            Iso3 = "PRT",
                            Name = "Portugal",
                            Numcode = 620,
                            PhoneCode = 351
                        },
                        new
                        {
                            Id = 173,
                            Iso = "PR",
                            Iso3 = "PRI",
                            Name = "Puerto Rico",
                            Numcode = 630,
                            PhoneCode = 1787
                        },
                        new
                        {
                            Id = 174,
                            Iso = "QA",
                            Iso3 = "QAT",
                            Name = "Qatar",
                            Numcode = 634,
                            PhoneCode = 974
                        },
                        new
                        {
                            Id = 175,
                            Iso = "RE",
                            Iso3 = "REU",
                            Name = "Reunion",
                            Numcode = 638,
                            PhoneCode = 262
                        },
                        new
                        {
                            Id = 176,
                            Iso = "RO",
                            Iso3 = "ROM",
                            Name = "Romania",
                            Numcode = 642,
                            PhoneCode = 40
                        },
                        new
                        {
                            Id = 177,
                            Iso = "RU",
                            Iso3 = "RUS",
                            Name = "Russian Federation",
                            Numcode = 643,
                            PhoneCode = 7
                        },
                        new
                        {
                            Id = 178,
                            Iso = "RW",
                            Iso3 = "RWA",
                            Name = "Rwanda",
                            Numcode = 646,
                            PhoneCode = 250
                        },
                        new
                        {
                            Id = 179,
                            Iso = "SH",
                            Iso3 = "SHN",
                            Name = "Saint Helena",
                            Numcode = 654,
                            PhoneCode = 290
                        },
                        new
                        {
                            Id = 180,
                            Iso = "KN",
                            Iso3 = "KNA",
                            Name = "Saint Kitts and Nevis",
                            Numcode = 659,
                            PhoneCode = 1869
                        },
                        new
                        {
                            Id = 181,
                            Iso = "LC",
                            Iso3 = "LCA",
                            Name = "Saint Lucia",
                            Numcode = 662,
                            PhoneCode = 1758
                        },
                        new
                        {
                            Id = 182,
                            Iso = "PM",
                            Iso3 = "SPM",
                            Name = "Saint Pierre and Miquelon",
                            Numcode = 666,
                            PhoneCode = 508
                        },
                        new
                        {
                            Id = 183,
                            Iso = "VC",
                            Iso3 = "VCT",
                            Name = "Saint Vincent and the Grenadines",
                            Numcode = 670,
                            PhoneCode = 1784
                        },
                        new
                        {
                            Id = 184,
                            Iso = "WS",
                            Iso3 = "WSM",
                            Name = "Samoa",
                            Numcode = 882,
                            PhoneCode = 685
                        },
                        new
                        {
                            Id = 185,
                            Iso = "SM",
                            Iso3 = "SMR",
                            Name = "San Marino",
                            Numcode = 674,
                            PhoneCode = 378
                        },
                        new
                        {
                            Id = 186,
                            Iso = "ST",
                            Iso3 = "STP",
                            Name = "Sao Tome and Principe",
                            Numcode = 678,
                            PhoneCode = 239
                        },
                        new
                        {
                            Id = 187,
                            Iso = "SA",
                            Iso3 = "SAU",
                            Name = "Saudi Arabia",
                            Numcode = 682,
                            PhoneCode = 966
                        },
                        new
                        {
                            Id = 188,
                            Iso = "SN",
                            Iso3 = "SEN",
                            Name = "Senegal",
                            Numcode = 686,
                            PhoneCode = 221
                        },
                        new
                        {
                            Id = 189,
                            Iso = "RS",
                            Iso3 = "SRB",
                            Name = "Serbia",
                            Numcode = -1,
                            PhoneCode = 381
                        },
                        new
                        {
                            Id = 190,
                            Iso = "SC",
                            Iso3 = "SYC",
                            Name = "Seychelles",
                            Numcode = 690,
                            PhoneCode = 248
                        },
                        new
                        {
                            Id = 191,
                            Iso = "SL",
                            Iso3 = "SLE",
                            Name = "Sierra Leone",
                            Numcode = 694,
                            PhoneCode = 232
                        },
                        new
                        {
                            Id = 192,
                            Iso = "SG",
                            Iso3 = "SGP",
                            Name = "Singapore",
                            Numcode = 702,
                            PhoneCode = 65
                        },
                        new
                        {
                            Id = 193,
                            Iso = "SK",
                            Iso3 = "SVK",
                            Name = "Slovakia",
                            Numcode = 703,
                            PhoneCode = 421
                        },
                        new
                        {
                            Id = 194,
                            Iso = "SI",
                            Iso3 = "SVN",
                            Name = "Slovenia",
                            Numcode = 705,
                            PhoneCode = 386
                        },
                        new
                        {
                            Id = 195,
                            Iso = "SB",
                            Iso3 = "SLB",
                            Name = "Solomon Islands",
                            Numcode = 90,
                            PhoneCode = 677
                        },
                        new
                        {
                            Id = 196,
                            Iso = "SO",
                            Iso3 = "SOM",
                            Name = "Somalia",
                            Numcode = 706,
                            PhoneCode = 252
                        },
                        new
                        {
                            Id = 197,
                            Iso = "ZA",
                            Iso3 = "ZAF",
                            Name = "South Africa",
                            Numcode = 710,
                            PhoneCode = 27
                        },
                        new
                        {
                            Id = 198,
                            Iso = "GS",
                            Name = "South Georgia and the South Sandwich Islands",
                            Numcode = -1,
                            PhoneCode = 0
                        },
                        new
                        {
                            Id = 199,
                            Iso = "ES",
                            Iso3 = "ESP",
                            Name = "Spain",
                            Numcode = 724,
                            PhoneCode = 34
                        },
                        new
                        {
                            Id = 200,
                            Iso = "LK",
                            Iso3 = "LKA",
                            Name = "Sri Lanka",
                            Numcode = 144,
                            PhoneCode = 94
                        },
                        new
                        {
                            Id = 201,
                            Iso = "SD",
                            Iso3 = "SDN",
                            Name = "Sudan",
                            Numcode = 736,
                            PhoneCode = 249
                        },
                        new
                        {
                            Id = 202,
                            Iso = "SR",
                            Iso3 = "SUR",
                            Name = "Suriname",
                            Numcode = 740,
                            PhoneCode = 597
                        },
                        new
                        {
                            Id = 203,
                            Iso = "SJ",
                            Iso3 = "SJM",
                            Name = "Svalbard and Jan Mayen",
                            Numcode = 744,
                            PhoneCode = 47
                        },
                        new
                        {
                            Id = 204,
                            Iso = "SZ",
                            Iso3 = "SWZ",
                            Name = "Swaziland",
                            Numcode = 748,
                            PhoneCode = 268
                        },
                        new
                        {
                            Id = 205,
                            Iso = "SE",
                            Iso3 = "SWE",
                            Name = "Sweden",
                            Numcode = 752,
                            PhoneCode = 46
                        },
                        new
                        {
                            Id = 206,
                            Iso = "CH",
                            Iso3 = "CHE",
                            Name = "Switzerland",
                            Numcode = 756,
                            PhoneCode = 41
                        },
                        new
                        {
                            Id = 207,
                            Iso = "SY",
                            Iso3 = "SYR",
                            Name = "Syrian Arab Republic",
                            Numcode = 760,
                            PhoneCode = 963
                        },
                        new
                        {
                            Id = 208,
                            Iso = "TW",
                            Iso3 = "TWN",
                            Name = "Taiwan, Province of China",
                            Numcode = 158,
                            PhoneCode = 886
                        },
                        new
                        {
                            Id = 209,
                            Iso = "TJ",
                            Iso3 = "TJK",
                            Name = "Tajikistan",
                            Numcode = 762,
                            PhoneCode = 992
                        },
                        new
                        {
                            Id = 210,
                            Iso = "TZ",
                            Iso3 = "TZA",
                            Name = "Tanzania, United Republic of",
                            Numcode = 834,
                            PhoneCode = 255
                        },
                        new
                        {
                            Id = 211,
                            Iso = "TH",
                            Iso3 = "THA",
                            Name = "Thailand",
                            Numcode = 764,
                            PhoneCode = 66
                        },
                        new
                        {
                            Id = 212,
                            Iso = "TL",
                            Iso3 = "TLS",
                            Name = "Timor-Leste",
                            Numcode = 626,
                            PhoneCode = 670
                        },
                        new
                        {
                            Id = 213,
                            Iso = "TG",
                            Iso3 = "TGO",
                            Name = "Togo",
                            Numcode = 768,
                            PhoneCode = 228
                        },
                        new
                        {
                            Id = 214,
                            Iso = "TK",
                            Iso3 = "TKL",
                            Name = "Tokelau",
                            Numcode = 772,
                            PhoneCode = 690
                        },
                        new
                        {
                            Id = 215,
                            Iso = "TO",
                            Iso3 = "TON",
                            Name = "Tonga",
                            Numcode = 776,
                            PhoneCode = 676
                        },
                        new
                        {
                            Id = 216,
                            Iso = "TT",
                            Iso3 = "TTO",
                            Name = "Trinidad and Tobago",
                            Numcode = 780,
                            PhoneCode = 1868
                        },
                        new
                        {
                            Id = 217,
                            Iso = "TN",
                            Iso3 = "TUN",
                            Name = "Tunisia",
                            Numcode = 788,
                            PhoneCode = 216
                        },
                        new
                        {
                            Id = 218,
                            Iso = "TR",
                            Iso3 = "TUR",
                            Name = "Turkey",
                            Numcode = 792,
                            PhoneCode = 90
                        },
                        new
                        {
                            Id = 219,
                            Iso = "TM",
                            Iso3 = "TKM",
                            Name = "Turkmenistan",
                            Numcode = 795,
                            PhoneCode = 7370
                        },
                        new
                        {
                            Id = 220,
                            Iso = "TC",
                            Iso3 = "TCA",
                            Name = "Turks and Caicos Islands",
                            Numcode = 796,
                            PhoneCode = 1649
                        },
                        new
                        {
                            Id = 221,
                            Iso = "TV",
                            Iso3 = "TUV",
                            Name = "Tuvalu",
                            Numcode = 798,
                            PhoneCode = 688
                        },
                        new
                        {
                            Id = 222,
                            Iso = "UG",
                            Iso3 = "UGA",
                            Name = "Uganda",
                            Numcode = 800,
                            PhoneCode = 256
                        },
                        new
                        {
                            Id = 223,
                            Iso = "UA",
                            Iso3 = "UKR",
                            Name = "Ukraine",
                            Numcode = 804,
                            PhoneCode = 380
                        },
                        new
                        {
                            Id = 224,
                            Iso = "AE",
                            Iso3 = "ARE",
                            Name = "United Arab Emirates",
                            Numcode = 784,
                            PhoneCode = 971
                        },
                        new
                        {
                            Id = 225,
                            Iso = "GB",
                            Iso3 = "GBR",
                            Name = "United Kingdom",
                            Numcode = 826,
                            PhoneCode = 44
                        },
                        new
                        {
                            Id = 226,
                            Iso = "US",
                            Iso3 = "USA",
                            Name = "United States",
                            Numcode = 840,
                            PhoneCode = 1
                        },
                        new
                        {
                            Id = 227,
                            Iso = "UM",
                            Name = "United States Minor Outlying Islands",
                            Numcode = -1,
                            PhoneCode = 0
                        },
                        new
                        {
                            Id = 228,
                            Iso = "UY",
                            Iso3 = "URY",
                            Name = "Uruguay",
                            Numcode = 858,
                            PhoneCode = 598
                        },
                        new
                        {
                            Id = 229,
                            Iso = "UZ",
                            Iso3 = "UZB",
                            Name = "Uzbekistan",
                            Numcode = 860,
                            PhoneCode = 998
                        },
                        new
                        {
                            Id = 230,
                            Iso = "VU",
                            Iso3 = "VUT",
                            Name = "Vanuatu",
                            Numcode = 548,
                            PhoneCode = 678
                        },
                        new
                        {
                            Id = 231,
                            Iso = "VE",
                            Iso3 = "VEN",
                            Name = "Venezuela",
                            Numcode = 862,
                            PhoneCode = 58
                        },
                        new
                        {
                            Id = 232,
                            Iso = "VN",
                            Iso3 = "VNM",
                            Name = "Viet Nam",
                            Numcode = 704,
                            PhoneCode = 84
                        },
                        new
                        {
                            Id = 233,
                            Iso = "VG",
                            Iso3 = "VGB",
                            Name = "Virgin Islands, British",
                            Numcode = 92,
                            PhoneCode = 1284
                        },
                        new
                        {
                            Id = 234,
                            Iso = "VI",
                            Iso3 = "VIR",
                            Name = "Virgin Islands, U.s.",
                            Numcode = 850,
                            PhoneCode = 1340
                        },
                        new
                        {
                            Id = 235,
                            Iso = "WF",
                            Iso3 = "WLF",
                            Name = "Wallis and Futuna",
                            Numcode = 876,
                            PhoneCode = 681
                        },
                        new
                        {
                            Id = 236,
                            Iso = "EH",
                            Iso3 = "ESH",
                            Name = "Western Sahara",
                            Numcode = 732,
                            PhoneCode = 0
                        },
                        new
                        {
                            Id = 237,
                            Iso = "YE",
                            Iso3 = "YEM",
                            Name = "Yemen",
                            Numcode = 887,
                            PhoneCode = 967
                        },
                        new
                        {
                            Id = 238,
                            Iso = "ZM",
                            Iso3 = "ZMB",
                            Name = "Zambia",
                            Numcode = 894,
                            PhoneCode = 260
                        },
                        new
                        {
                            Id = 239,
                            Iso = "ZW",
                            Iso3 = "ZWE",
                            Name = "Zimbabwe",
                            Numcode = 716,
                            PhoneCode = 263
                        },
                        new
                        {
                            Id = 240,
                            Iso = "ME",
                            Iso3 = "MNE",
                            Name = "Montenegro",
                            Numcode = -1,
                            PhoneCode = 382
                        });
                });

            modelBuilder.Entity("Trifon.IDP.Entities.UserSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSecrets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Trifon.IDP.Entities.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Trifon.IDP.Entities.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Trifon.IDP.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trifon.IDP.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Trifon.IDP.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trifon.IDP.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Trifon.IDP.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Trifon.IDP.Entities.UserSecret", b =>
                {
                    b.HasOne("Trifon.IDP.Entities.ApplicationUser", "User")
                        .WithMany("Secrets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trifon.IDP.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Secrets");
                });
#pragma warning restore 612, 618
        }
    }
}
